from typing import TypeVar

from _typeshed import Incomplete

from . import sql as sql

_T = TypeVar("_T")

class Error(Exception): ...

class Connection[T]:
    @classmethod
    def connect(cls, *args: Incomplete, **kwargs: Incomplete) -> Connection[dict[str, object]]: ...
    def __enter__(self) -> Connection[_T]: ...
    def __exit__(self, *args: object) -> None: ...
    def cursor(self, *args: Incomplete, **kwargs: Incomplete) -> Incomplete: ...
    def execute(self, *args: Incomplete, **kwargs: Incomplete) -> Incomplete: ...

def connect(*args: Incomplete, **kwargs: Incomplete) -> Connection[dict[str, object]]: ...
