from _typeshed import Incomplete

class Composable: ...

class SQL(Composable):
    def __init__(self, value: str) -> None: ...
    def format(self, *args: Incomplete, **kwargs: Incomplete) -> SQL: ...
    def join(self, seq: Incomplete) -> SQL: ...

class Identifier:
    def __init__(self, *values: str) -> None: ...

class Placeholder:
    def __init__(self, name: str = ...) -> None: ...
