# SPDX-FileCopyrightText: 2026 Blackcat Informatics® Inc. <paudley@blackcat.ca>
# SPDX-License-Identifier: AGPL-3.0-only

extends: default
rules:
  comments: disable
  comments-indentation: disable
  document-start: disable
  line-length:
    allow-non-breakable-inline-mappings: true
    allow-non-breakable-words: true
    max: 88
  truthy:
    allowed-values:
      - 'true'
      - 'false'
    check-keys: false
