from _typeshed import Incomplete

class ConnectionPool:
    def __init__(self, *args: Incomplete, **kwargs: Incomplete) -> None: ...
    def connection(self) -> Incomplete: ...
    def close(self) -> None: ...
    def get_stats(self) -> dict[str, Incomplete]: ...
