from _typeshed import Incomplete

class PyGraph:
    def __init__(self, *args: Incomplete, **kwargs: Incomplete) -> None: ...
    def add_node(self, node: Incomplete) -> int: ...
    def add_edge(self, source: Incomplete, target: Incomplete, edge: Incomplete) -> Incomplete: ...
    def add_nodes_from(self, nodes: Incomplete) -> Incomplete: ...
    def add_edges_from(self, edges: Incomplete) -> Incomplete: ...
    def num_nodes(self) -> int: ...
    def num_edges(self) -> int: ...

class PyDiGraph(PyGraph): ...

def digraph_dijkstra_shortest_paths(*args: Incomplete, **kwargs: Incomplete) -> dict[int, list[int]]: ...
def digraph_dijkstra_shortest_path_lengths(*args: Incomplete, **kwargs: Incomplete) -> dict[int, float]: ...
def pagerank(*args: Incomplete, **kwargs: Incomplete) -> dict[int, float]: ...
def digraph_betweenness_centrality(*args: Incomplete, **kwargs: Incomplete) -> dict[int, float]: ...
def digraph_closeness_centrality(*args: Incomplete, **kwargs: Incomplete) -> dict[int, float]: ...
def digraph_degree_centrality(*args: Incomplete, **kwargs: Incomplete) -> dict[int, float]: ...
def in_degree_centrality(*args: Incomplete, **kwargs: Incomplete) -> dict[int, float]: ...
def out_degree_centrality(*args: Incomplete, **kwargs: Incomplete) -> dict[int, float]: ...
def digraph_eigenvector_centrality(*args: Incomplete, **kwargs: Incomplete) -> dict[int, float]: ...
def digraph_katz_centrality(*args: Incomplete, **kwargs: Incomplete) -> dict[int, float]: ...
def strongly_connected_components(*args: Incomplete, **kwargs: Incomplete) -> list[set[int]]: ...
def weakly_connected_components(*args: Incomplete, **kwargs: Incomplete) -> list[set[int]]: ...
def simple_cycles(*args: Incomplete, **kwargs: Incomplete) -> list[list[int]]: ...
