from collections.abc import Callable

def chunkerify(name: str, chunk_size: int) -> Callable[[str], list[str]]: ...
def chunk(text: str, *, chunk_size: int, token_counter: Callable[[str], int], overlap: int) -> list[str]: ...
