from _typeshed import Incomplete

class SchemaBuilder:
    def add_text_field(self, *args: Incomplete, **kwargs: Incomplete) -> Incomplete: ...
    def add_unsigned_field(self, *args: Incomplete, **kwargs: Incomplete) -> Incomplete: ...
    def build(self) -> Schema: ...

class Index:
    def __init__(self, *args: Incomplete, **kwargs: Incomplete) -> None: ...
    @classmethod
    def create(cls, *args: Incomplete, **kwargs: Incomplete) -> Incomplete: ...
    @classmethod
    def open(cls, *args: Incomplete, **kwargs: Incomplete) -> Incomplete: ...
    @classmethod
    def exists(cls, *args: Incomplete, **kwargs: Incomplete) -> bool: ...

class Document:
    def __init__(self, **kwargs: Incomplete) -> None: ...
    @classmethod
    def from_dict(cls, value: dict[str, list[str]]) -> Document: ...

class Schema: ...
