from typing import Any

class SchemaBuilder:
    def add_text_field(self, name: str, *, stored: bool = ...) -> Any: ...
    def add_unsigned_field(self, *args: Any, **kwargs: Any) -> Any: ...
    def build(self) -> Schema: ...

class Schema: ...

class Index:
    schema: Schema

    def __init__(self, schema: Schema, *, path: str = ...) -> None: ...
    @classmethod
    def create(cls, *args: Any, **kwargs: Any) -> Any: ...
    @classmethod
    def open(cls, path: str) -> Index: ...
    @classmethod
    def exists(cls, path: str) -> bool: ...
    def writer(self) -> Any: ...
    def searcher(self) -> Any: ...
    def parse_query_lenient(self, query: str, fields: list[str]) -> tuple[Any, Any]: ...
    def reload(self) -> None: ...

class Document:
    def __init__(self, **kwargs: Any) -> None: ...
    @classmethod
    def from_dict(cls, value: dict[str, Any]) -> Document: ...
    def get_first(self, name: str) -> Any: ...
