class ZstdCompressor:
    def __init__(self, *args: object, **kwargs: object) -> None: ...
    def compress(self, data: bytes) -> bytes: ...

class ZstdDecompressor:
    def __init__(self, *args: object, **kwargs: object) -> None: ...
    def decompress(self, data: bytes) -> bytes: ...
