# SPDX-FileCopyrightText: 2026 Blackcat Informatics® Inc.
# SPDX-License-Identifier: AGPL-3.0-only

from contextlib import AbstractContextManager
from typing import Any

class _Config:
    config_file_name: str | None
    config_ini_section: str

    def get_main_option(self, name: str) -> str: ...
    def get_section(self, name: str, default: dict[str, Any] = ...) -> dict[str, Any]: ...

config: _Config

def configure(**kwargs: Any) -> None: ...
def run_migrations() -> None: ...
def begin_transaction() -> AbstractContextManager[Any]: ...
def is_offline_mode() -> bool: ...
