# SPDX-FileCopyrightText: 2026 Blackcat Informatics® Inc.
# SPDX-License-Identifier: MIT

from typing import Any

def execute(query: Any) -> None: ...
def create_table(name: str, *columns: Any, **kwargs: Any) -> None: ...
def drop_table(name: str) -> None: ...
def create_index(name: str, table_name: str, columns: list[str], **kwargs: Any) -> None: ...
def drop_index(name: str, table_name: str = ..., **kwargs: Any) -> None: ...
def add_column(table_name: str, column: Any) -> None: ...
def drop_column(table_name: str, column_name: str) -> None: ...
def alter_column(table_name: str, column_name: str, **kwargs: Any) -> None: ...
def create_foreign_key(name: str, source: str, referent: str, local_cols: list[str], remote_cols: list[str], **kwargs: Any) -> None: ...
def drop_constraint(name: str, table_name: str, **kwargs: Any) -> None: ...
def create_unique_constraint(name: str, table_name: str, columns: list[str], **kwargs: Any) -> None: ...
def create_check_constraint(name: str, table_name: str, condition: Any, **kwargs: Any) -> None: ...
def rename_table(old: str, new: str) -> None: ...
def get_bind() -> Any: ...
