# SPDX-FileCopyrightText: 2026 Blackcat Informatics® Inc.
# SPDX-License-Identifier: MIT

from typing import Any

class TestClient:
    def __init__(self, app: Any, base_url: str = ...) -> None: ...
    def get(self, url: str, *, headers: dict[str, str] | None = ...) -> Any: ...
    def post(self, url: str, *, headers: dict[str, str] | None = ..., json: Any = ...) -> Any: ...
    def put(self, url: str, *, headers: dict[str, str] | None = ..., json: Any = ...) -> Any: ...
    def delete(self, url: str, *, headers: dict[str, str] | None = ...) -> Any: ...
    def patch(self, url: str, *, headers: dict[str, str] | None = ..., json: Any = ...) -> Any: ...
