from _typeshed import Incomplete

class TfidfVectorizer:
    def __init__(self, *args: Incomplete, **kwargs: Incomplete) -> None: ...
    def fit_transform(self, documents: list[str]) -> Incomplete: ...
    def get_feature_names_out(self) -> list[str]: ...
