from collections.abc import Callable
from typing import TypeVar

from _typeshed import Incomplete

_F = TypeVar("_F", bound=Callable[..., object])

class FastMCP:
    def __init__(self, name: str) -> None: ...
    def tool(self, *args: Incomplete, **kwargs: Incomplete) -> Callable[[_F], _F]: ...
    def resource(self, uri: str, **kwargs: Incomplete) -> Callable[[_F], _F]: ...
    def streamable_http_app(self) -> Incomplete: ...
