# SPDX-FileCopyrightText: 2026 Blackcat Informatics® Inc.
# SPDX-License-Identifier: MIT

"""Versioned Alembic migrations for the Gmeow database schema.

Each module in this package is a single Alembic revision generated by ``alembic revision`` and
reviewed before landing. Revisions are immutable once merged; roll forward with a new revision
rather than amending an existing one.

See Also:
    MODULE.md: Migration revisions conventions.

"""
