from _typeshed import Incomplete

class KMeans:
    labels_: list[int]
    def __init__(self, *args: Incomplete, **kwargs: Incomplete) -> None: ...
    def fit(self, data: Incomplete) -> Incomplete: ...

class DBSCAN:
    labels_: list[int]
    def __init__(self, *args: Incomplete, **kwargs: Incomplete) -> None: ...
    def fit(self, data: Incomplete) -> Incomplete: ...
