class Credentials:
    @classmethod
    def from_authorized_user_info(cls, info: dict[str, object], scopes: list[str]) -> Credentials: ...
    @classmethod
    def from_authorized_user_file(cls, filename: str, scopes: list[str]) -> Credentials: ...
