class Credentials:
    @classmethod
    def from_service_account_info(cls, info: dict[str, object], scopes: list[str]) -> Credentials: ...
    @classmethod
    def from_service_account_file(cls, filename: str, scopes: list[str]) -> Credentials: ...
    def with_subject(self, subject: str) -> Credentials: ...
